- name: Create pihole directory
  file:
    path: "/home/{{ ansible_user }}/pihole"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: 0755

- name: Create 2nd pihole directory
  file:
    path: "/home/{{ ansible_user }}/pihole/pihole"
    state: directory

- name: Ensure /home/{{ ansible_user }}/pihole/var/log/lighttpd directory
  file:
    path: "/home/{{ ansible_user }}/pihole/var/log/lighttpd"
    state: directory
    mode: 0777

- name: Ensure /home/{{ ansible_user }}/pihole/var/log/lighttpd log files
  file:
    path: "/home/{{ ansible_user }}/pihole/var/log/lighttpd/{{item}}.log"
    state: touch
    mode: 0766
  with_items:
    - error
    - access

- name: Create FTL config
  blockinfile:
    path: "/home/{{ ansible_user }}/pihole/pihole/pihole-FTL.conf"
    create: yes
    block: MAXDBDAYS={{ pihole_ftl_max_db_days }}

- name: Get IPv6 link local address
  set_fact:
    ipv6: "{{ item.address }}"
  loop: "{{ vars['ansible_' + default_ipv6_interface].ipv6 }}"
  loop_control:
    label: "{{ item.address }}"
  when: "'link' in item.scope"

- name: Start/Update pihole container
  docker_container:
    name: pihole
    image: "{{ pihole_image }}"
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    env:
      TZ: "{{ timezone }}"
      ServerIP: "0.0.0.0"
      ServerIPv6: "::"
      WEBPASSWORD: "{{ pihole_webpassword }}"
      PIHOLE_DNS_: "{{ pihole_dns }}"
      DNSSEC: "{{ pihole_dnssec }}"
      DNSMASQ_LISTENING: "local"
      REV_SERVER: "{{ pihole_rev_server }}"
      REV_SERVER_DOMAIN: "{{ pihole_rev_server_domain }}"
      REV_SERVER_TARGET: "{{ pihole_rev_server_target }}"
      REV_SERVER_CIDR: "{{ pihole_rev_server_cidr }}"
    dns_servers:
      - 127.0.0.1
      - "{{ static_dns }}"
    network_mode: host
    volumes:
      - "/home/{{ ansible_user }}/pihole/etc/pihole/:/etc/pihole/"
      - "/home/{{ ansible_user }}/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/"
      - "/home/{{ ansible_user }}/pihole/var/log:/var/log"
      - "/home/{{ ansible_user }}/pihole/var/log/lighttpd:/var/log/lighttpd"
    log_driver: json-file
    log_options:
      max-size: "10m"
      max-file: "5"

- name: Check pihole container
  uri:
    url: http://localhost
  register: result
  until: result.status == 200
  retries: 5
  delay: 10

- name: Remove old image versions
  docker_prune:
    images: yes
    images_filters:
      dangling: false

- name: ATTENTION!!!
  debug:
    msg:
      - "Make sure to point your DNS server settings to this Pi-hole:"
      - "DNSv4: {{ ansible_host }}"
      - "DNSv6: {{ ipv6 }}"
      - ""
      - "In the HA setup with keepalived, these are your settings:"
      - "DNSv4: {{ pihole_vip_ipv4.split('/')[0] }}"
      - "DNSv6: {{ pihole_vip_ipv6.split('/')[0] }}"
